//
//  MoodList.swift
//  Filmr
//
//  Created by Dritani on 2016-04-02.
//  Copyright © 2016 AquariusLB. All rights reserved.
//

import Foundation

struct MoodList {
    
    static let Moods:[String:[String]]! = [
        "😀": [
            "Airplane!",
            "Coming to America",
            "The Hangover",
            "Shaun of the Dead",
            "Clueless",
            "Ghostbusters",
            "Zoolanderp ding Crashers",
            "Anchorman",
            "Hot Fuzz",
            "American Pie 2",
            "Ted",
            "Crazy Stupid Love",
            "50 First Dates",
            "Austin Powers",
            "Spaceballs",
            "The Breakfast Club",
            "Toy Story 3",
            "Up",
            "The LEGO Movie",
            "Ratatouille",
            "The Truman Show",
            "Juno"
        ],
        
        "⭐": [
            "The Shawshank Redemption",
            "The Godfather",
            "The Godfathe: Part II",
            "The Dark Knight",
            "Schindler's List",
            "12 Angry Men",
            "Pulp Fiction",
            "The Lord of the Rings: The Return of the King",
            "Fight Club",
            "Forrest Gump",
            "Inception",
            "Goodfellas",
            "The Matrix",
            "City of God",
            "Se7en",
            "The Usual Suspects",
            "Spirited Away",
            "Saving Private Ryan",
            "Interstellar",
            "The Departed",
            "Memento",
            "Apocalypse Now",
            "The Prestige",
            "Django Unchained",
            "WALL-E",
            "Oldboy",
            "Full Metal Jacket",
            "Deadpool",
            "Zootopia"
        ],
        
        "🚗": [
            "The Dark Knight",
            "Casino Royale",
            "The Matrix",
            "The Avengers",
            "The Raid",
            "The Bourne Ultimatum",
            "Die Hard",
            "Raiders of the Lost Ark",
            "Terminator",
            "Aliens",
            "Battle Royale",
            "Mission Impossible",
            "The Dark Knight Rises",
            "Avengers: Age of Ultron",
            "Mad Max: Fury Road",
            "Kill Bill Volume 1",
            "Taken",
            "Total Recall",
            "Braveheart",
            "Gladiator"
        ],
        
        "😱": [
            "Halloween",
            "The Exorcist",
            "It Follows",
            "The Babadook",
            "Scream",
            "Night of the Living Dead",
            "The Shining",
            "Let the Right One In",
            "Dawn of the Dead",
            "The Blair Witch Project",
            "The Texas Chainsaw Massacre",
            "The Cabin in the Woods",
            "A Nightmare on Elm Street",
            "Alien",
            "You're Next",
            "Psycho",
            "The Evil Dead",
            "Hellraiser",
            "The House of the Devil",
            "Creep",
            "Rosemary's Baby",
            "The Visit",
            "Ring",
            "The Omen",
            "The Conjuring",
            "Insidious",
            "Suspiria",
            "Crimson Peak",
            "The Thing",
            "The Silence of The Lambs",
            "We are Still Here",
            "Goodnight Momy",
            "The Fly",
            "We are what we are",
            "The Ring",
            "The Orphanage",
            "The Strangers",
            "Poltergeist",
            "28 Days Later",
            "The Others",
            "Jaws"
        ],
            
        "😍": [
            "The Notebook",
            "When Harry Met Sally",
            "Titanic",
            "Love Actually",
            "Eternal Sunshine of the Spotless Mind",
            "Pretty Woman",
            "Bridget Jones's Diary",
            "Dirty Dancing",
            "Four Weddings and a Funeral",
            "Silver Linings Playbook",
            "Before Sunset",
            "Blue is the Warmest Colour",
            "500 Days of Summer",
            "10 Things I Hate About You",
            "Moonrise Kingdom"
        ],
            
        "💩": [
            "The, Room",
            "Showgirls",
            "Battlefield Earth",
            "Glen or Glenda?",
            "Plan 9 from Outer Space",
            "Robot Monster",
            "Howling II",
            "The Black Gestapo",
            "Frankenstein Island",
            "Road House",
            "Maniac",
            "The Giant Claw",
            "Terror of Tiny Town",
            "Satan's Sadists",
            "Shark Attack 3: Megalodon",
            "The Roller Blade Seven",
            "Ishtar",
            "Troll 2",
            "Manos: The Hands of Fate",
            "For your Height Only",
            "Batman & Robin",
            "Mommie Dearest",
            "The Oscar",
            "Giant Spider Invasion",
        ],
        
        "🎄": [
            "Elf",
            "A Christmas Story",
            "Home Alone",
            "It's a Wonderful Life",
            "The Nightmare Before Christmas",
            "Love Actually",
            "National Lampoon's Christmas Vacation",
            "The Santa Clause",
            "The Polar Express",
            "Bad Santa",
            "Miracle on 34th Street",
            "A Charlie Brown Christmas",
            "Scrooged",
            "The Holiday",
            "The Muppet Christmas Carol",
            "White Christmas",
            "Jingle All the Way",
            "Gremlins",
            "Home Alone 2: Lost in New York",
            "Christmas with the Kranks",
            "Rudolph the Red-Nosed Reindeer",
            "Die Hard",
            "Frosty the Snowman",
            "Dr. Seuss' How the Grinch Stole Christmas",
            "Arthur Christmas",
            "Edward Scissorhands",
            "Holiday Inn",
            "Meet me in St. Louis",
            "The Ref",
            "The Bishop's Wife",
            "Rare Exports: A Christmas Tale",
            "Fred Claus",
            "A Christmas Tale",
            "A Christmas Carol",
            "The Santa Clause 2",
            "Lethal Weapon",
            "Ernest Saves Christmas",
            "Mickey's Christmas Carol",
            "Happy Christmas",
            "The Best Man Holiday",
            "Santa Claus: The Movie",
            "I'll Be Home for Christmas"
        ],
        
        "🚬": [
            "Up in Smoke",
            "How High",
            "Half Baked",
            "Friday",
            "Next Friday",
            "Friday after Next",
            "Ted",
            "Grandma's Boy",
            "Super High Me",
            "Dazed and Confused",
            "The Big Lebowski",
            "Harold & Kumar",
            "Super Troppers",
            "Pineapple Express",
            "Soul Plane",
            "Fear and Loathing in Las Vegas",
            "This is the End",
            "Knocked Up",
            "Tenacious D in the Pick of Destiny",
            "We're the Millers",
            "Mac & Devin go to High School",
            "Cheech & Chong's Animated Movie",
            "High School",
            "Dude, Where's my Car?",
            "Jay and Silent Bob Strike Back",
            "Your Highness",
            "Puff, Puff, Pass",
            "Rolling Kansas",
            "Evil Bong",
            "Evil Bong II: King Bong",
            "Growing Op",
            "The Wash",
            "Kid Cannabis",
            "Strange Wilderness",
            "Road Trip",
            "Pulp Fiction",
            "Trailer Park Boys",
            "Smiley Face",
            "Beetlejuice",
            "Tank Girl",
            "Ghost World",
            "Fight Club",
            "Nowhere",
            "In Bruges"
            

        ],
    ]
    
}